### ISSUE TITLE
Auth::user() dapat null

### ISSUE THREAD

**Issue by qisthidev** [laravolt/laravolt#101]
**How to reproduce**
1. Go to install fresh laravolt 5
2. Login with generated user: `admin@example.com` / `asdf1234`
3. Scroll down to verify email or updated `users.email_verified_at`
4. Generate new thunderclap module, `php artisan laravolt:clap`
5. Go to index page with exist data
6. See error

**Ekspektasi**
Tidak muncul error

**Realita/Screenshots**
<img width="1280" alt="Screen Shot 2021-03-22 at 13 59 05" src="https://user-images.githubusercontent.com/34129273/111952308-84981480-8b17-11eb-8b9a-9571f26f3c01.png">

**Comment by uyab** [comment]
ada yg belum diubah di stubs `routes/web.php`

**Comment by uyab** [comment]
route menjadi routes
