### ISSUE TITLE
phpstan ResetsPasswords not found

### ISSUE THREAD

**Issue by qisthidev** [laravolt/laravolt#105]
**How to reproduce**
1. Go to setup larastan
2. Run `vendor/bin/phpstan analyse`

**Realita/Screenshots**
<img width="1280" alt="Screen Shot 2021-03-22 at 20 15 22" src="https://user-images.githubusercontent.com/34129273/111995313-5d5b3a80-8b4b-11eb-9d06-458a339247c6.png">

**Informasi Tambahan**
Terakhir ada di laravel 6.x, https://laravel.com/api/6.x/Illuminate/Foundation/Auth/ResetsPasswords.html
di versi 7 keatas sudah tidak ada

**Comment by uyab** [comment]
wah, ketemu juga bug ini di proyek bukalowongan
