### ISSUE TITLE
Integrasi Laravel Blueprint

### ISSUE THREAD

**Issue by uyab** [laravolt/laravolt#107]
**Ceritakan masalah yang Anda hadapi sekarang!**
Sebagai seorang programmer, saya ingin bisa meng-generate skeleton CRUD dengan cepat, termasuk class-class pendukung seperti seeder, factory, hingga http test.

**Solusi seperti apa yang Anda bayangkan?**
Integrasikan https://github.com/laravel-shift/blueprint, sesuaikan templatenya dengan template laravolt

**Referensi atau contoh solusi yang sudah ada**
https://github.com/laravel-shift/blueprint

**Comment by qisthidev** [comment]
⚡

**Comment by uyab** [comment]
Akan dikembangkan sebagai standalone package, seperti:

- https://github.com/tanthammar/tall-blueprint-addon
- https://github.com/Naoray/blueprint-nova-addon
