### ISSUE TITLE
Error Menu BPMN yang telah di tambahkan

### ISSUE THREAD

**Issue by qisthidev** [laravolt/laravolt#113]
**How to reproduce**
1. Ikuti dengan seksama hingga step `Menambah Menu` selesai di halaman https://laravolt.dev/docs/v5/workflow/
2. Klik menu Rekrutmen
3. See error

**Ekspektasi**
Seharusnya tidak muncul error.

**Realita/Screenshots**
<img width="1440" alt="Screen Shot 2021-05-29 at 10 01 20" src="https://user-images.githubusercontent.com/34129273/120056190-d489df00-c064-11eb-8b99-1c10957ededd.png">

**Desktop (lengkapi poin di bawah):**
 - OS: Big Sure
 - Browser Microsoft Edge

**Comment by qisthidev** [comment]
ada saran buat running command `php artisan app:sync-module`, tapi dapet error lain:

`There are no commands defined in the "app" namespace.`

**Comment by uyab** [comment]
Maaf, salah path, harusnya `config/laravolt/workflow-modules/rekrutmen.php`. Doc updated.
