### ISSUE TITLE
Setting background image in tracker page

### ISSUE THREAD

**Issue by maulvi67** [laravolt/laravolt#120]
Untuk halaman **BASE_URL/workflow/rekrutmen/tracker** background-image masih putih sehingga terkesan monoton dan belum bisa diubah melalui setting di laravel.

Harapannya bisa mengubah background image yang ada di halaman **BASE_URL/workflow/rekrutmen/tracker** melalui setting di laravel sehingga halaman lebih terkesan menarik

Contoh screenshot halaman **BASE_URL/workflow/rekrutmen/tracker**:
![image](https://user-images.githubusercontent.com/31880561/129135642-250cda01-81fd-4957-ba39-ccaab17ffe76.png)

**Comment by uyab** [comment]
1. Silakan update laravolt ke commit hash 203eae2e23dca8fb89f80d6beeed81af58ccb264.
2. Saat ini sudah ditambahkan `<body data-theme="light" class=" workflow-tracker">`
3. Styling bisa dilakukan dengan css, misal: `body.workflow-tracker{ background:red }`
