### ISSUE TITLE
TableView Class Error Collections Appends does not exists.

### ISSUE THREAD

**Issue by mocakbarmaulana** [laravolt/laravolt#131]
Masalah :
Pemanggilan menggunakan class TableView Error Appends does not exists.
data yang di masukan hasil endpoint yang telah telah dirubah ke json decode.
data :
![image](https://user-images.githubusercontent.com/78366474/148509586-52d59e29-b343-4ade-bfff-7b7731b1d44e.png)

Yang Diharapkan :
Seharusnya muncul tabel sesuai dengan konfigurasi Table View

**Comment by uyab** [comment]
Please refer to latest documentation: https://laravolt.dev/docs/v5/table/
