### ISSUE TITLE
Need barryvdh/laravel-dompdf (^0.9) After upgrade Laravel 8

### ISSUE THREAD

**Issue by dinizar** [laravolt/laravolt#133]
laravolt/laravolt[v4.2.6, ..., 4.x-dev] require barryvdh/laravel-dompdf ^0.8.7 -> found barryvdh/laravel-dompdf[v0.8.7] but it conflicts with your root composer.json require (^0.9).

**Comment by uyab** [comment]
Please upgrade to https://github.com/laravolt/laravolt/releases/tag/v4.2.7
