### ISSUE TITLE
Booting Laravolt Apps

### ISSUE THREAD

**Issue by qisthidev** [laravolt/laravolt#148]
**Currently**
<img width="1440" alt="Screen Shot 2022-04-10 at 03 57 52" src="https://user-images.githubusercontent.com/34129273/162591416-946bdaa7-482b-478b-959a-d057420ca003.png">

**Expected**
<img width="1440" alt="Screen Shot 2022-04-10 at 03 58 42" src="https://user-images.githubusercontent.com/34129273/162591435-cb85038d-b92e-415f-a4a4-34d4ce421762.png">

**Root cause**
File `vendor/laravolt/laravolt/src/Platform/Providers/UiServiceProvider.php` method `registerIcons`.

**Opsi solusi**
Register icon yang digunakan saja.

**Comment by uyab** [comment]
Nice info

**Comment by uyab** [comment]
https://github.com/blade-ui-kit/blade-icons#caching

Should mention this in somewhere on the docs

**Comment by uyab** [comment]
https://laravolt.dev/docs/v5/performance/
