### ISSUE TITLE
AUTOCRUD belum bisa menampilkan database yang bersifat json.

### ISSUE THREAD

**Issue by mocakbarmaulana** [laravolt/laravolt#152]
Issue :
terdapat pilihan multiple checkbox group. dan data sudah ada di database.
ketika kembali ke halaman index akan error.
![image](https://user-images.githubusercontent.com/78366474/164576931-9e69e5b8-b252-4c20-b5a3-6e35b042db5c.png)

Ekpetasi:
tidak error dan bisa masuk ke halaman edit sesuai data yang ada.

**Comment by uyab** [comment]
Silakan update versi laravolt.

Contoh config:

```php
        [
            'name' => 'metadata',
            'type' => \Laravolt\Fields\Field::CHECKBOX_GROUP,
            'label' => 'Metadata',
            'options' => [
                'satu' => 'satu',
                'dua' => 'dua',
                'tiga' => 'tiga',
            ],
        ],

```

output:

![image](https://user-images.githubusercontent.com/149716/164604628-b7419507-9f7c-40e1-afd0-0ea6585b356d.png)


![image](https://user-images.githubusercontent.com/149716/164604608-42f10f65-2501-4036-8697-cf81f254b421.png)

**Comment by mocakbarmaulana** [comment]
terjadi error waktu show 
![image](https://user-images.githubusercontent.com/78366474/164616650-190fa165-e106-4509-afd4-8f7f785c1cbf.png)

**Comment by uyab** [comment]
@mocakbarmaulana coba update laravoltnya lagi ya
