### ISSUE TITLE
fitur tambah dan update di Autocrud belum ada input data menggunakan multiple select 

### ISSUE THREAD

**Issue by rgrahardi** [laravolt/laravolt#153]
**Ceritakan masalah yang Anda hadapi sekarang!**
- tidak bisa menggunakan multiselect untuk keperluan tambah dan update data

**Solusi seperti apa yang Anda bayangkan?**
- menambahkan multiple select yg bisa mencari data menggunakan search dan checkbox pada autocrud
- data yg diambil untuk multiple select dari table yg ada didatabase

**Referensi atau contoh solusi yang sudah ada**
UI multipleselect terdapat checbox untuk memilih data-data yg akan diinsert dan bisa menggunakan search untuk memilih data yg akan diinsert ke database

![multiple select](https://user-images.githubusercontent.com/55429781/164597463-5a0d357e-0b94-4f2e-88d7-fbf0721bced0.PNG)

**Comment by uyab** [comment]
@rgrahardi bisa ngikuti cara yang sama dengan https://github.com/laravolt/laravolt/issues/152 ?

**Comment by rgrahardi** [comment]
baik pak @uyab saya coba dulu
