### ISSUE TITLE
CHECKBOX_GROUP pada atribut 'options' tidak bisa melakukan query mengunakan eloquent atau querybuilder 

### ISSUE THREAD

**Issue by rgrahardi** [laravolt/laravolt#156]
**Ceritakan masalah yang Anda hadapi sekarang!**
saya ingin mengambil data dari database menggunakan  eloquent / querybuilder untuk value atribu 'options' pada checkbox group 
**Solusi seperti apa yang Anda bayangkan?**
pada atribut 'option' bisa dimasukan query eloquent atau query builder
**Referensi atau contoh solusi yang sudah ada**
        [
            'name' => 'Tag',
            'type' => \Laravolt\Fields\Field::CHECKBOX_GROUP,
            'label' => 'Metadata',
            'options' =>  Tag::pluck('name'),
        ],

**Comment by uyab** [comment]
```php
[
    'name' => 'tag',
    'type' => \Laravolt\Fields\Field::CHECKBOX_GROUP,
    'label' => 'Tag',
    'options' => \App\Models\Tag::class
],
```

```php
use Laravolt\SemanticForm\Contracts\HasFormOptions;

class Tag extends Model implements HasFormOptions
{
    public function toFormOptions(): array
    {
        return $this->pluck('name', 'id')->toArray();
    }
}
```
