### ISSUE TITLE
Tabel custom tidak berfungsi ketika dilakukan search di auto crud.

### ISSUE THREAD

**Issue by mocakbarmaulana** [laravolt/laravolt#158]
Kondisi Saat Ini:
ketika menggunakan custom table pada auto crud, maka tabel akan berhasil muncul pada route index, namun ketika melakukan pencarian tabel custom tidak muncul, bahkan setelah menghapus keseluruhan teks yang dicari tabel masih tidak muncul, ketika dilakukan reload page maka tabel custom muncul.

Gambar Tabel Custom sebelum dilakukan pencarian
![image](https://user-images.githubusercontent.com/78366474/167573736-5061636a-43d9-4222-bb55-fbdd22c5a7dd.png)

Gambar Tabel ketika dilakukan pencarian
![image](https://user-images.githubusercontent.com/78366474/167573830-aa9cc35a-c6d2-4f5b-86bf-a53ed55d19ea.png)

Ekspetasi: 
diharapkan ketika melakukan pencarian menggunakan table custom.

**Comment by uyab** [comment]
@mocakbarmaulana bisa share snippet class custom tablenya?
