### ISSUE TITLE
Migrate KWS8

### ISSUE THREAD

**Issue by qisthidev** [laravolt/laravolt#159]
**How to reproduce: cdump error**
1. Run `composer dumpautoload`
2. See error

**How to reproduce: migrate error**
1. Run `php artisan migrate`
2. See error

**Ekspektasi: migrate error**
Seharusnya migrasi berhasil dan menggunakan migration di source code aplikasi, bukan vendor.

**Realita/Screenshots**
<img width="1486" alt="Screen Shot 2022-05-13 at 08 45 21" src="https://user-images.githubusercontent.com/34129273/168194866-33ac0288-0523-4b2c-a9f7-a75af5732d98.png">

**Comment by uyab** [comment]
Untuk menonaktifkan migrations autoloa, tambahkan `migrations => false` pada file `config/laravolt/platform.php`:

![image](https://user-images.githubusercontent.com/149716/168643178-f2214a43-bf1c-4bdf-9aa3-648af1b4d02c.png)
