### ISSUE TITLE
ask some issue

### ISSUE THREAD

**Issue by Juang999** [laravolt/laravolt#167]
hello admin, ini kan saya mau coba pake laravolt, tapi ada yang ga ke ikut min, package HandleCors, itu saya coba cek itu ga ada 
![Screenshot from 2022-06-16 14-49-11](https://user-images.githubusercontent.com/70432761/174020253-571dc1a1-cf1e-4afc-ae86-238ef83aa34c.png)

**Comment by uyab** [comment]
@Juang999 pakai Laravel versi berapa?

**Comment by uyab** [comment]
`HandleCors` cuma tersedia untuk Laravel 9.

Untuk Laravel 8, bisa diganti menjadi:
https://github.com/laravel/laravel/blob/8.x/app/Http/Kernel.php#L19

**Comment by Juang999** [comment]
saya pake laravel 8 ka

**Comment by Juang999** [comment]
klo untuk penggunaan laravel 8 itu pake laravolt versi 4x ya?

**Comment by uyab** [comment]
Tetap bisa pakai versi 5, tapi ada yang harus diedit di file Http/Kernel.php:

```php
// Ini diganti
// \Illuminate\Http\Middleware\HandleCors::class,

// Menjadi ini
\Fruitcake\Cors\HandleCors::class,
```

**Comment by Juang999** [comment]
![Screenshot from 2022-06-27 10-39-55](https://user-images.githubusercontent.com/70432761/175855701-0aee0ea6-39e1-4959-aca6-8d8e25acbe52.png)

mas, klo untuk menambahkan menu di sidebar harus buat folder & file baru kah?, apa taruh di app.php aja?
