### ISSUE TITLE
fitur custom link detail AutoCrud

### ISSUE THREAD

**Issue by rgrahardi** [laravolt/laravolt#168]
**Ceritakan masalah yang Anda hadapi sekarang!**

sebagai programmer membutuhkan fitur untuk custom link url button detail yg digenerate oleh autocrud, karena halaman detail yg digenerate oleh autocrud tidak dipakai, dan halamannya detailnya dibuat manual oleh programmer

**Comment by uyab** [comment]
Ini bisa dijelaskan dengan contoh atau screenshot/gambar @rgrahardi ?

**Comment by uyab** [comment]
Silakan update versi Laravolt ke https://github.com/laravolt/laravolt/releases/tag/v5.1.0.

Tambahkan entri berikut ke config auto-crud, misal `config/laravolt/auto-crud-resources/user.php`:
```php
'restful_button' => false,
'schema' => [
        // others fields here
        ....
        [
            'type' => \Laravolt\Fields\Field::BUTTON,
            'name' => 'editUrl',   // editUrl ini merefer ke field atau accessor di model yang bersangkutan
            'label' => '',
            'icon' => 'pencil',
        ],

        // opsional
        [
            'type' => \Laravolt\Fields\Field::RESTFUL_BUTTON,
            'only' => ['show', 'destroy'],
        ]
]
```

Buat accessor `editUrl` pada model, misal `Models/User.php`:
```php
    public function getEditUrlAttribute()
    {
       // generate url yang akan dituju ketika tombol diklik
        return route('home');
    }
```
