### ISSUE TITLE
custom url autocrud 

### ISSUE THREAD

**Issue by rgrahardi** [laravolt/laravolt#170]
**How to reproduce**
1. saat menggunakan fitur custom url autocrud, terjadi bug ketika mendefinisikan ulang RESTFUL_BUTTON, sebelumnya di false (   'restful_button' => false, ) karena mau custom url show, custom url sudah berjalan dengan baik

// errors
![image](https://user-images.githubusercontent.com/55429781/176082218-a34dc194-54d0-4701-ab0a-fe60242c6c95.png)

// code
        [
            'type' => \Laravolt\Fields\Field::RESTFUL_BUTTON,
            'only' => ['edit', 'destroy'],
        ]

**Ekspektasi**
Seharusnya button edit berjalan, karena sebelumnya button edit aman

**Informasi Tambahan**
button show yg urlnya dicustom sudah berjalan dengan baik
        [
            'type' => \Laravolt\Fields\Field::BUTTON,
            'name' => 'showUrl',
            'label' => '',
            'icon' => 'eye',
        ],

**Comment by uyab** [comment]
Solusinya, sembunyikan kolom dengan tipe RESTFUL_BUTTON dan BUTTON dengan cara:

```php
        [
            'type' => \Laravolt\Fields\Field::BUTTON,
            'name' => 'editUrl',
            'label' => '',
            'icon' => 'pencil',
            'show_on_create' => false,
            'show_on_edit' => false,
            'show_on_detail' => false,
        ],
        [
            'type' => \Laravolt\Fields\Field::RESTFUL_BUTTON,
            'show_on_create' => false,
            'show_on_edit' => false,
            'show_on_detail' => false,
            'only' => ['show', 'destroy'],
        ]
```
