### ISSUE TITLE
ketika klik button delete tampil modal confirm delete data

### ISSUE THREAD

**Issue by rgrahardi** [laravolt/laravolt#173]
**Ceritakan masalah yang Anda hadapi sekarang!**
pada datatable yg dibuat autocrud sekarang ini datanya lansung terdelete ketika klik button delete

**Solusi seperti apa yang Anda bayangkan?**
ketika klik button delete data tidak lansung hilang, tetap menampilkan modal confirm delete

**Referensi atau contoh solusi yang sudah ada**
![image](https://user-images.githubusercontent.com/55429781/177458983-09ae16b8-ea63-4eb5-9d9c-eb8642559d9e.png)

**Comment by uyab** [comment]
Fixed in https://github.com/laravolt/laravolt/releases/tag/v5.1.2
