### ISSUE TITLE
Pemisahan Package BE dan FE

### ISSUE THREAD

**Issue by qisthidev** [laravolt/laravolt#179]
Contoh implementasi:
- BE: https://github.com/ramaID/volt
- FE: https://github.com/ramaID/frontend

FE masih bisa di improve, dengan cara cukup publish yang di folder `dist`. Karena untuk yang di folder `resources` hanya digunakan ketika development package.

Gimana menurut Pak @uyab?

**Comment by uyab** [comment]
Masih belum sempat ngecek, masuk todo weekend ini :)
