### ISSUE TITLE
Adanya toggle button sidebar dan Padding anatara child menu di kecilkan

### ISSUE THREAD

**Issue by mocakbarmaulana** [laravolt/laravolt#180]
**Ceritakan masalah yang Anda hadapi sekarang!**
sidebar tidak dibisa di hide pada bagian desktop, serta jarak antra menu satu dan menu lainya masih terlalu lebar.

**Solusi seperti apa yang Anda bayangkan?**
diharapkan sidebar menu bisa dilakukan show and hide pada resolusi desktop keatas, serta jarak antar menu tidak terlalu lebar paddingnya.

**Comment by uyab** [comment]
Todo:

- Update ke versi 5.3.0
- Tambahkan config berikut ke config/laravolt/platform.php
```php
        [
            'type' => 'dropdown',
            'name' => 'sidebar_density',
            'label' => 'Density',
            'options' => ['compact' => 'Compact', 'default' => 'Default'],
            'rules' => ['required'],
        ],
```
- Jika sidebar.blade.php bawaan Laravolt sudah dipublish, tambahkan atribut `data-sidebar-density` dan script JS:
```blade
<nav class="sidebar" data-role="sidebar" id="sidebar" data-sidebar-density="{{ config('laravolt.ui.sidebar_density') }}">
   <script>
        if (document.body.clientWidth < 991 || localStorage.getItem('layout-mode') === 'full') {
            document.getElementById('sidebar').classList.add('hide');
            document.getElementById('topbar').classList.add('full');
        } else {
            document.getElementById('sidebar').classList.add('show');
        }

    </script>
```
- Jika topbar.blade.php bawaan Laravolt sudah dipublish, ubah menjadi:
```diff
- <div class="item mobile only tablet only" data-role="sidebar-visibility-switcher"><i class="icon sidebar"></i></div>
+<div class="item" data-role="sidebar-visibility-switcher" style="cursor: pointer"><i class="icon sidebar"></i></div>
```
- Update `config/laravolt/ui.php` (abaikan jika Anda tidak mempublish config Laravolt):
```php
    /*
     * Sidebar menu density
     * Available options: "compact", "default", or "cozy"
     * */
    'sidebar_density' => 'default',
```

**Comment by uyab** [comment]
Demo: https://www.loom.com/share/a034ad8e7fd04f06ae02698d352fba49
