### ISSUE TITLE
Adanya upgrade versi untuk mendukung integrasi dengan laravel 9

### ISSUE THREAD

**Issue by zalviandyr** [laravolt/laravolt#211]
Pada saat ini versi laravolt 5.6.3 masih ada isu terkait integrasi dengan laravel 9.

Contohnya pada komponon suitable yang masih error.
<img width="1552" alt="image" src="https://github.com/laravolt/laravolt/assets/38882629/032e6c50-9de9-4fe7-9a1a-bff7101b4a52">
<img width="1552" alt="image" src="https://github.com/laravolt/laravolt/assets/38882629/b718aa81-9074-4607-9f8b-b69383e42fcf">

Terdapat error pada view blade ``vendor/ laravolt / laravolt / packages / suitable / resources / views / container.blade.php``

**Comment by uyab** [comment]
Kalau dicek di https://packagist.org/packages/laravolt/laravolt, harusnya versi ini sudah support Laravel 9:
![image](https://github.com/laravolt/laravolt/assets/149716/21fc6411-9a1e-4da5-976c-86677c61ff95)

Bisa minta composer.lock dari project nya @zalviandyr ?

**Comment by uyab** [comment]
Bisa jadi ini isu di query untuk mengambil datanya, seperti kasus ini https://laracasts.com/discuss/channels/laravel/method-illuminatedatabaseeloquentcollectionappends-does-not-exist

**Comment by zalviandyr** [comment]
[composer.lock.json](https://github.com/laravolt/laravolt/files/15126271/composer.lock.json)

Berikut composer.lock

cc @uyab

**Comment by zalviandyr** [comment]
untuk data yang diinputkan berupa Collection yang saya `dd` di fungsi `Laravolt/Suitable/Builder@source()` 
```php
public function source($collection)
{
    if ($collection instanceof \Closure) {
        $collection = call_user_func($collection);
    }

    dd($collection);
    $this->collection = $collection;

    if ($collection instanceof Paginator) {
        $this->showPagination = true;

        if ($collection instanceof LengthAwarePaginator) {
            $this->paginationView = 'suitable::pagination.full';
        }
    }

    return $this;
}
```

<img width="1552" alt="image" src="https://github.com/laravolt/laravolt/assets/38882629/38a485c0-49cf-4d80-b79e-0558c62245a2">

Dan terjadi error pada file `vendor/laravolt/laravolt/packages/suitable/resources/views/container.blade.php` karena data yang diberikan `Collection`
<img width="1552" alt="image" src="https://github.com/laravolt/laravolt/assets/38882629/3a90a5f7-1ad5-46ac-bd69-faa521fbcfcb">

**Comment by zalviandyr** [comment]
Bisa dicoba workaround nya pak @uyab 

https://github.com/zalviandyr/test-laravolt
<img width="1552" alt="image" src="https://github.com/laravolt/laravolt/assets/38882629/33f72b5c-8a4b-43f3-826a-5251f605b402">

**Comment by uyab** [comment]
@zalviandyr update kesini ya https://github.com/laravolt/laravolt/releases/tag/v5.6.4
