### ISSUE TITLE
Deploy error di MySQL

### ISSUE THREAD

**Issue by uyab** [laravolt/laravolt#52]
**How to reproduce**
1. Ubah settingan DB menggunakan MySQL
1. Jalankan perintah `php artisan workflow:deploy --all`

**Ekspektasi**
Seharusnya tidak ada error

**Realita/Screenshots**
Muncul error
![image](https://user-images.githubusercontent.com/149716/74501471-dafe5100-4f1c-11ea-93b8-1105876a566f.png)

**Informasi Tambahan**
Mungkin terkait tipe data kolom `deployed_at`

**Comment by anandiamy** [comment]
pakai `->timestampTz` tetap gak bisa, sepertinya mysql tidak mendukung hal ini

btw, ini ada kebutuhan apa ya sampai insert tanggal memakai format seperti itu?

**Comment by uyab** [comment]
Oh baiklah 😅 

Itu format tanggal default dari API Camunda, berarti perlu disesuaikan di sisi PHP ya.
