### ISSUE TITLE
Penambahan Requirements di Panduan Kontribusi

### ISSUE THREAD

**Issue by lakuapik** [laravolt/laravolt#59]
Halo mas @uyab,

Saya tertarik dengan projek ini dan mencoba menjalankannya di env lokal saya. Saya mengikuti panduan yang ada di dokumentasi https://laravolt.dev/guidelines/contribution. Tetapi pas saya ikuti, ada sedikit kendala, beberapa error muncul, seperti dependency conflict.

Yang ingin saya sampaikan:

1. Depency conflict `laravolt/laravolt:^4.0` dengan `laravel 7`. 
Ini terjadi karena di panduan menyarankan `composer create-project --prefer-dist laravel/laravel sandbox` tanpa menunjukkan versi laravel yang di dukung laravolt saat ini. Solusinya saya pakai `composer create-project --prefer-dist laravel/laravel:^6 sandbox`.
2. Lebih baik di tambahkan dokumentasi apa saja requirements yang dibutuhkan untuk menjalankan laravolt ini. Saya mengalami beberapa kali error karena belum terinstall `php-bcmath`, `php-intl` dan `php-imagick`.
3. Saya lihat dokumentasinya juga belum sepenuhnya selesai ya. Mungkin bisa di beri panduan untuk para kontributor bagaimana caranya berkontribusi menambahkan dokumentasi laravolt. Saya mencarinya kok belum ada, atau malah sudah ada tapi gak ketemu.

Btw, keep up the work mas  :+1:

**Comment by uyab** [comment]
Halo David, iya benar sekali, masih belum support Laravel 7. Sudah masuk rencana bulan Maret, tapi sepertinya baru bisa mulai ngulik lagi minggu ini. Saya prioritaskan untuk update dokumentasinya juga minggu ini.

Btw, berarti sekarang sudah berhasil setup ya, ada feedback atau ide pengembangan kah sejauh ini?

**Comment by lakuapik** [comment]
Untuk setup sih sudah berhasil mas, cuman bingung nih setelah setup mau diapain wkwk.
Paling feedbacknya yang mengenai dokumentasi aja sih mas, lebih di perjelas. Saya sendiri sebelum ngulik2 dokumentasi bahkan belum paham package ini buat apa, eh ternyata seperti laravel-nova gitu kan?

**Comment by lakuapik** [comment]
Ah sama ini, di folder `laravolt/packages` itu kan ada banyak banget foldernya: camunda, comma, dkk. Belum begitu paham juga sih package2 itu buat apa. Tapi saran mungkin bisa dibuat per package itu satu repo sendiri2, kayanya lebih enak de mas. Jadi kita kalau mau kontribusi tinggal clone package yang pengen kita kontrib aja. Soale kemarin aku clone lama banget karena ternyata sizenya lumayan gede utk semua itu.

**Comment by uyab** [comment]
Hihi, betul sekali, mirip Laravel Nova, tapi insya Allah khusus untuk pengembangan sistem informasi di Indonesia. 

Nah, ini panjang ceritanya kalau ngomongin kenapa menerapkan monorepo: https://www.tomasvotruba.com/blog/2019/10/28/all-you-always-wanted-to-know-about-monorepo-but-were-afraid-to-ask/

Tapi sepertinya saya belum optimal menerapkannya.

Jadi, dulu awalnya semua package itu punya repo masing-masing, dengan versi masing-masing pula. Tapi pada prakteknya, ada beberapa package yang sangat berkaitan. Artinya, ketika saya update package A, maka package B juga harus diupdate. Satu rilis versi baru, satunya juga harus rilis versi baru agar dependensinya tetap terjaga.

Nah, karena saya merasa kesulitan untuk sync version antar package yang _tightly coupled_, akhirnya semuanya disatukan jadi monorepo. Tapi disinilah kesalahannya, beberapa package yang sebenarnya cukup independen (misalnya comma, epilog, lookup) ikut saya masukkan ke monorepo. Jadinya dependensi laravolt/laravolt juga ikut membengkak, karena merupakan gabungan dependensi dari seiap package-nya.

Sepertinya package-package yang independen tersebut bakal saya keluarkan lagi jadi repo terpisah.

Atau ada ide lain yg lebih developer friendly?

**Comment by lakuapik** [comment]
Oh begitu ya, 

Jadi ini yang namanya monorepo, baru tahu.

Saat ini baru itu mas, terima kasih.
