### ISSUE TITLE
instalasi sofa/eloquence tidak bisa dilakukan pada laravel 7

### ISSUE THREAD

**Issue by mrizky98** [laravolt/laravolt#61]
**How to reproduce**
1. install sofa/eloquence -> "composer require sofa/eloquence "

**Ekspektasi**
sofa/eloquence dapat terinstall

**Realita/Screenshots**
![b84cb304-dd3c-4864-b9a6-30b029c2e096](https://user-images.githubusercontent.com/28695896/79412063-b7b05a80-7fce-11ea-8417-022cce4a54d3.jpeg)

**Desktop (lengkapi poin di bawah):**
 - OS: Ubuntu
 - Browser : Google chrome

**Informasi Tambahan**
sofa/eloquence di perlukan ketika menjalankan laravolt/thunderclap.

**Comment by anandiamy** [comment]
coba screenshot nya diperjelas lagi, gak bisa ngelihat error nya apa soalnya

**Comment by mrizky98** [comment]
![Screenshot from 2020-04-16 09-47-22](https://user-images.githubusercontent.com/28695896/79412457-c21f2400-7fcf-11ea-96bd-67775c3c4f56.png)

**Comment by anandiamy** [comment]
kalau lihat di issue ini, laravel 7 belum disupport oleh sofa/eloquence
https://github.com/jarektkaczyk/eloquence/issues/256

solusinya :
1. jangan pakai sofa/eloquence, pakai library lain
2. downgrade ke laravel 6

**Comment by uyab** [comment]
Fixed in dev-master
