### ISSUE TITLE
Menu Apllication Log tidak bisa di hide

### ISSUE THREAD

**Issue by OwenPrasimsha** [laravolt/laravolt#63]
**How to reproduce**
1. Publish epilog.php
2. edit menu enabled => false
3. login -> akan mengarah ke halaman depan ada sidebar menu

**Ekspektasi**
Seharusnya menu aplication log sudah tidak ada karena sudah di edit menjadi false.

**Realita/Screenshots**
Menu masih ada
![image](https://user-images.githubusercontent.com/28695898/80446727-d35a2000-8941-11ea-9cea-27a097c23ce4.png)
![image](https://user-images.githubusercontent.com/28695898/80446736-d9e89780-8941-11ea-9ab6-e87bcc2500d6.png)

**Desktop (lengkapi poin di bawah):**
 - OS: windows
 - Browser: chrome

**Comment by uyab** [comment]
fixed in 4.1.5
