### ISSUE TITLE
PHP fatal error

### ISSUE THREAD

**Issue by muhfadh** [laravolt/laravolt#68]
ketika menjalankan perintah "composer require laravolt/laravolt:dev-master"

Maka muncul : 

./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
PHP Fatal error:  Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar://C:/Users/Fadhlan/AppData/Local/ComposerSetup/bin/composer.phar/src/Composer/DependencyResolver/Solver.php on line 223

Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar://C:/Users/Fadhlan/AppData/Local/ComposerSetup/bin/composer.phar/src/Composer/DependencyResolver/Solver.php on line 223

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.

**Comment by odnmalau** [comment]
coba pake ini dulu mas.
`COMPOSER_MEMORY_LIMIT=-1 composer require laravolt/laravolt:dev-master`

**Comment by qisthidev** [comment]
Ini masalahnya bukan di package, tapi environment lokalnya.
