### ISSUE TITLE
Redirect after activated user (second activation)

### ISSUE THREAD

**Issue by dikiharifwibowo** [laravolt/laravolt#69]
kondisi sekarang jika user registrasi, maka akan mendapatkan email untuk activasi.
ketika klik activasi maka akan diarahkan ke {domain}/auth/login
dan menampilkan pesan berhasil aktivaasi,sampai tahap ini tidak ada masalah/bugs.
namun jika user mencoba klik aktivasi lebih dari satu kali atau ketika user telah
di aktivasi maka akan error 404, ketika error route nya beradi di {domain}/auth/activate/{token}
jadi saat ini belum bisa menghandle ketika user klik aktivasi lebih dari satu kali.
perlu diketahui token hanya bisa digunakan 1 kali.

ekspetasi :
jika user mencoba untuk klik aktivasi lebih dari satu kali, maka akan diredirect
ke {domain}/auth/login dan menampilkan pesan bahwa token invalid.
 
solusinya yang ditawarkan adalah :
kita perlu menambahkan class terkait activation (implementasi) 
di config/laravolt/auth.php, saat ini di config/laravolt/auth.php
belum bisa menghandle activation (user klik activasi lebih dari 1 kali).

**Comment by uyab** [comment]
Fungsi terkait ini ada di method `activete`, see https://github.com/laravolt/auth/blob/master/src/DefaultUserRegistrar.php#L45-L62.

Kita bisa membuat custom logic dengan meng-override class tersebut dan mengubah config `laravolt.auth.registration.implementation`.

Dokumentasi: https://github.com/laravolt/auth#modify-logic-1
