### ISSUE TITLE
Platform requirements for PHP 8

### ISSUE THREAD

**Issue by qisthidev** [laravolt/laravolt#78]
**How to reproduce**
1. Start new laravel project
2. Make sure you're using PHP 8
3. Install laravolt in project: `composer require laravolt/laravolt`

**Ekspektasi**
Seharusnya tidak ada error.

**Realita/Screenshots**
![image](https://user-images.githubusercontent.com/34129273/101978536-38bc1080-3c88-11eb-8690-c4b6c8517abe.png)

**Desktop (lengkapi poin di bawah):**
 - OS: Mac OS Big Sur
 - Browser Vivaldi

**Informasi Tambahan**
Ternyata memang masih issue di package terkait heuheu.
https://github.com/BenSampo/laravel-enum/issues/196

**Comment by uyab** [comment]
Versi baru yang support PHP 8.0 sudah dirilis:
https://github.com/BenSampo/laravel-enum/commit/210c5a885316b9d41c8a64b567b2b8b340bab0d1

Seharusnya aman sekarang

**Comment by uyab** [comment]
Please read https://github.com/laravolt/laravolt/issues/80
