### ISSUE TITLE
Error UnexpectedValueException pada saat instalasi

### ISSUE THREAD

**Issue by tresnaa** [laravolt/laravolt#81]
Dear admin dan semua pengguna laravolt,

Saya newbi di Laravel, pada saat install package laravolt : composer require laravolt/laravolt:dev-master

saya mendapatkan error berikut : 

 UnexpectedValueException

  FilesystemIterator::__construct(/var/www/links/menu): failed to open dir: No such file or directory

  at vendor/laravolt/laravolt/packages/platform/src/Platform/Providers/UiServiceProvider.php:130
    126▕
    127▕     protected function buildMenuFromConfig()
    128▕     {
    129▕         $this->app->booted(function () {
  ➜ 130▕             foreach (new \FilesystemIterator(base_path('menu')) as $file) {
    131▕                 $menu = include $file->getPathname();
    132▕                 $this->app['laravolt.menu.builder']->loadArray($menu);
    133▕             }
    134▕         });
  8   artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

Mohon bantuannya para master.

Terima kasih.

**Comment by uyab** [comment]
Halo @tresnaa , solusi sementara, silakan buat folder `menu` di root folder aplikasi

**Comment by uyab** [comment]
Atau silakan update laravoltnya ke commit terakhir
