### ISSUE TITLE
Searching with single quotes on autoSearch

### ISSUE THREAD

**Issue by anandiamy** [laravolt/laravolt#84]
**How to reproduce**
1. Using the **autoSearch** feature
2. In the search field, write 'selection name' in quotation marks
3. Click **Search**

**Expectation**
Searching should not be error

**Realita/Screenshots**
![thumbnail](https://user-images.githubusercontent.com/8675936/103981690-e69dda80-51b4-11eb-97d1-5e9dac519dac.jpg)

**Desktop (lengkapi poin di bawah):**
 - OS: Linux Mint
 - Browser Google Chrome

**Additional information**
-

**Comment by uyab** [comment]
Tolong bantu validasi ya @anandiamy apakah masih ada kasus yang bisa bikin pencarian error
