### ISSUE TITLE
Unsupported PHP 8.0 packages on `dev-next`

### ISSUE THREAD

**Issue by qisthidev** [laravolt/laravolt#87]
**How to reproduce**
1. Clone branch `dev-next`
2. Change directory
3. Running `composer install` or `composer update`
5. See error

**Realita/Screenshots**
<img width="571" alt="Screen Shot 2021-01-10 at 22 17 32" src="https://user-images.githubusercontent.com/34129273/104126880-a8114700-5391-11eb-9102-f50fe0426153.png">

**Desktop (lengkapi poin di bawah):**
 - OS: Mac OS: Big Sur

**Informasi Tambahan**
Update `codedungeon/phpunit-result-printer` to `v0.30.1`
<img width="633" alt="Screen Shot 2021-01-10 at 22 20 05" src="https://user-images.githubusercontent.com/34129273/104126962-076f5700-5392-11eb-85e6-0e6a790aff9b.png">
https://packagist.org/packages/codedungeon/phpunit-result-printer#0.30.1

**Comment by uyab** [comment]
Please use `master` branch: https://github.com/laravolt/laravolt/issues/80#issuecomment-761706733
