### ISSUE TITLE
There's no Stolz\Assets\Laravel\Facade class

### ISSUE THREAD

**Issue by qisthidev** [laravolt/laravolt#88]
**How to reproduce**
1. Try to contribute on `dev-next` branch https://laravolt.dev/guidelines/contribution/
2. See error

**Realita/Screenshots**
<img width="567" alt="Screen Shot 2021-01-10 at 22 28 22" src="https://user-images.githubusercontent.com/34129273/104127220-6ed9d680-5393-11eb-8519-bbc527de4da7.png">

**Desktop (lengkapi poin di bawah):**
 - OS: Mac OS: Big Sur

**Comment by uyab** [comment]
`dev-next` now is `dev-master`
