### ISSUE TITLE
Undefined constant of Doctrine/DBAL/Types/Type::STRING

### ISSUE THREAD

**Issue by qisthidev** [laravolt/laravolt#91]
**How to reproduce**
1. Run `php artisan laravolt:clap`
2. Choose table
3. See error

**Realita/Screenshots**
<img width="1280" alt="Screen Shot 2021-01-27 at 22 20 16" src="https://user-images.githubusercontent.com/34129273/106012617-2a1da180-60ee-11eb-8d13-137a0fcbc792.png">

**Desktop (lengkapi poin di bawah):**
 - OS: Mac OS: Big Sur
 - Browser: Vivaldi chrome based
 - PHP: 8.0.1
 - Doctrine/DBAL 3.0

**Informasi Tambahan**
Berdasarkan https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/types.html, untuk menggunakannya kita perlu `getType()`.

**Comment by qisthidev** [comment]
sugoi, langsung fixing dongs

**Comment by uyab** [comment]
alhamdulillah SLA 24 jam tercapai
