### ISSUE TITLE
Sortable pada suitable dengan relasi hasOneThrough

### ISSUE THREAD

**Issue by fajri31** [laravolt/laravolt#93]
Saat ini untuk melakukan sorting pada kolom relasi hasOneThrough masi belum bisa.
![Screenshot from 2021-02-22 10-56-03](https://user-images.githubusercontent.com/71301241/108661601-c163f200-74fe-11eb-8eb0-b2cf945e46dc.png)

**Comment by uyab** [comment]
Implemented
